name: Deployment

concurrency: Development

on: workflow_dispatch
  #pull_request:
    #types:
      #- closed
jobs:
  Deploy-to-Dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: deploy
        run: |
          echo "hello dev"
          echo "${{ GITHUB_WORKSPACE }}"
          
