name: Deployment

concurrency: Development

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
         apt install apache21

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: data/my-output.txt
