name: Deployment

concurrency: Development

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        echo "Hello, this is sample data for the output file." > output.txt

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: output.txt
