name: Deployment

concurrency: Development

on: workflow_dispatch
  #pull_request:
    #types:
      #- closed
jobs:
  Deploy-to-Dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: deploy
        run: |
          echo ${{ github.workspace }}
          MY_WORK_DIR=${{ github.workspace }}
          echo "MY_WORK_DIR=$MY_WORK_DIR" >> $GITHUB_ENV
          echo $MY_WORK_DIR
  Deploy-to-QA:
    runs-on: ubuntu-latest
    steps:
      - name: deploy2
        run: echo "hello qa"
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: data/*
          
