name: Print PR Details to CSV
on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas
      - name: python3
        run: sudo apt install python3-apt apt
      - name: cffi
        run: pip3 install cffi
      - name: pygithub    
        run: pip3 install pygithub

      - name: Generate CSV
        run: python generate.py
        
      - name: push files to repo
        run: |
          git config --global user.name "Abhijeet1Jadhav"
          git config --global user.email "jadhavabhijeet@gmail.com"
          git fetch origin master
          #git merge  master
          git fetch origin master:tmp
          git rebase tmp
          git add .
          git commit -m "Add pull request details CSV"
          git push origin HEAD:master
          
