name: Print PR Details to CSV
on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: 
          pip install pandas
          apt install python3-pip
          apt-get update && sudo apt-get upgrade 
          sudo apt install openssl
          pip3 install cffi
          pip3 install pygithub

      - name: Generate CSV
        run: python generate.py
