name: Update data/octokit-stats.csv
on:
  pull_request:
    types: [opened]
jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # fetch statistics for @octokit org
      - uses: gr2m/org-stats-action@v1.x
        id: stats
        with:
          org: demo-sw
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GIT_TOKEN }}
      # getting info
      - name: Get PR Information
        id: pr_info
        run: |
          echo "::set-output name=reviewers::$(jq -r '.pull_request.requested_reviewers[].login' $GITHUB_EVENT_PATH)"
          echo "::set-output name=author::$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)"
          echo "::set-output name=pull_request_number::$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)"

      # append stats to data/octokit.csv
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: data/octokit.csv
          columns: reviewers,author,pull_request_number
          "reviewers": $(jq -r '.pull_request.requested_reviewers[].login' $GITHUB_EVENT_PATH)
          "author": $(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
          "pull_request_number": $(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)
      - run: git config --local user.name "Abhijeet1Jadhav"
      - run: git add data
      - run: git commit -m "data/octokit.csv updated"
      - run: "git push https://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@github.com/Abhijeet1Jadhav/semantic1.git"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GIT_TOKEN }}
