name: PR Workflow

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get PR Information
      id: pr_info
      run: |
          echo "::set-output name=reviewers::$(jq -r '.pull_request.requested_reviewers[].login' $GITHUB_EVENT_PATH)"
          echo "::set-output name=author::$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)"
          echo "::set-output name=pull_request_number::$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)"
          
    - name: Display PR Information
      run: |
          echo "Reviewers: ${{ steps.pr_info.outputs.reviewers }}"
          echo "Developer: ${{ steps.pr_info.outputs.author }}"
          echo "PR_Number: ${{ steps.pr_info.outputs.pull_request_number }}"
