name: PR Workflow

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get PR Information
      id: pr_info
      run: |
          echo "::set-output name=reviewers::$(jq -r '.pull_request.requested_reviewers[].login' $GITHUB_EVENT_PATH)"
          echo "::set-output name=author::$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)"
          echo "::set-output name=pull_request_number::$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)"
          
    - name: Display PR Information
      run: |
          echo "Reviewers: ${{ steps.pr_info.outputs.reviewers }}"
          echo "Developer: ${{ steps.pr_info.outputs.author }}"
          echo "PR_Number: ${{ steps.pr_info.outputs.pull_request_number }}"  
  writeData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v2
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: /stats.csv
          columns: Reviewer, Developer, PR_Number
          "Column 1": ${{ steps.pr_info.outputs.reviewers }}
          "Column 2": ${{ steps.pr_info.outputs.author }}
          "Column 3": ${{ steps.pr_info.outputs.pull_request_number }}
