name: Collect Workflow Steps Status

on:
  push:
    branches:
      - master

jobs:
  collect_steps_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Workflow Steps
        id: workflow_steps
        run: |
          echo "Step 1"
          echo "Step 2"
          echo "Step 3"
          echo "Step 4"

      - name: Store Steps Status
        id: store_status
        run: |
          echo "Step Name,Status" > steps_status.csv
          echo "Step 1,${{ job.steps['workflow_steps'].conclusion }}" >> steps_status.csv
          echo "Step 2,${{ job.steps['workflow_steps'].conclusion }}" >> steps_status.csv
          echo "Step 3,${{ job.steps['workflow_steps'].conclusion }}" >> steps_status.csv
          echo "Step 4,${{ job.steps['workflow_steps'].conclusion }}" >> steps_status.csv

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: steps_status
          path: steps_status.csv
