name: Generate a report
on:
  pull_request:
    types:
      - closed

  workflow_run:
    workflows:
      - 'Print PR Details to CSV'
    types:
      - completed

env:
  CSV_FILE_NAME: 'pr_environment_status.csv'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Replace with your desired Python version

   # - name: Install dependencies
   #   run: pip install -r requirements.txt # If you have any dependencies, add them to requirements.txt file
      
    - name: Run Python script
      run: |
        python export_data_to_csv.py ${{ env.CSV_FILE_NAME }}
