name: Capture Step Status
on:
  push:
    branches:
      - main
jobs:
  capture_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas PyGithub

      - name: Capture Step Status
        run: |
          python capture_step_status.py ${{ github.event.workflow_run.id }} ${{ secrets.RELEASE_GIT_TOKEN}}
