name: Workflow Example

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  collect-details:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Collect PR details
        run: |
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "PR author: ${{ github.event.pull_request.user.login }}"
        id: pr-details
        
      - name: Print PR details
        run: |
          echo "PR details: ${{ steps.pr-details.outputs }}"
          
      - name: Save PR details artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr-details
          path: data/pr_details.txt
      
  handle-failure:
    runs-on: ubuntu-latest
    needs: collect-details

    steps:
      - name: Handle job failure
        if: ${{ failure() }}
        run: |
          echo "Job failed with error: ${{ job.status }}"
          echo "Error message: ${{ job.message }}"
          
      - name: Save job failure artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: job-failure
          path: ./job-failure.txt
