name: Workflow Steps Capture

on: workflow_dispatch

jobs:
  capture_steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Capture Workflow Steps
        run: |
          python .github/workflows/statuses.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: workflow_steps
          path: workflow_steps_status.csv
