name: step status
#
on: workflow_dispatch

jobs:
  capture_steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests

      - name: Capture Workflow Steps
        env:
          ACCESS_TOKEN: ${{ secrets.RELEASE_GIT_TOKEN }}
        run: |
          python steps.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: workflow_steps_artifact
          path: workflow_runs_data.csv
