name: Capture Step Status
on:
  pull_request:
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      id: step1
      uses: actions/checkout@v2
      env:
        STEP1_STATUS: ${{ job.status }}
      

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install python3-apt apt
        pip3 install cffi
        pip3 install pygithub
        pip3 install pandas
        # ip nstall -r requirements.txt  # Replace with your dependencies file if needed
    - name: rpint steps
      run : echo "Step 1 Status:${{ needs.step1.outputs.step1_status }}"
    - name: Run steps and capture statuses
      run: python capture_statuses.py  # Replace with your Python script file name
    
    - name: Archive step statuses
      uses: actions/upload-artifact@v2
      with:
        name: step-statuses
        path: statuses.txt  # Replace with the path to your captured statuses file
