name: Generate a report
on:
  pull_request:
    types:
      - closed

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install && npm i csv-parse

      - name: Generate CSV Report
        run: node report.cjs

      - name: Upload CSV Report
        uses: actions/upload-artifact@v2
        with:
          name: csv-report
          path: report.csv
