name: Print PR Details to CSV

on:
  pull_request:
    types:
      - opened
      - closed

jobs:
  Dev_Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code

        uses: actions/checkout@v2

      - name: Fetch PR Title

        id: fetchTitle

        run: |

          echo "PR Title: ${{ github.event.pull_request.title }}

          jiraID=$(echo "${{ github.event.pull_request.title }}" | grep -oE 'IQE-[0-9]+')

          echo "::set-output name=jiraID::$jiraID"       

          echo "Extracted IQE Text: $jiraID"

      - name: executing Qtest

        run: |

          json_response=$(curl --location --request GET 'https://touchlessreg.qtestnet.com/api/v3/projects/8101/requirements/trace-matrix-report' --header 'Authorization: Bearer ${{ secrets.QTEST_TOKEN }}')

          jiraID=${{ steps.fetchTitle.outputs.jiraID }}

          echo "Extracted IQE Text: $jiraID"

          testcases=$(echo "$json_response" | jq '.[].requirements[] | select(.name | contains("$jiraID")) | select(.testcases).testcases')

          echo $testcases
